### ISSUE TITLE
crash when loaded through game title

### ISSUE THREAD

**Issue by jul2003** [switchbrew/nx-hbloader#11]
Hi,

My setting is , CFW atmosphere official 0.7.3 loaded with fusee-primary.bin
hbloader official release 2.0.1 , put hbl.nsp in atmosphere folder
hbmenu official release 3.0.0 at the root of the sd card.
Switch in 4.0.1 firmware
SD card exfat formatted

Try to load hbmenu through zelda botw it crashes.
Same issue as in described in https://github.com/Atmosphere-NX/Atmosphere/issues/253
loader.ini 
[config]
hbl_tid=01007EF00011E000
hbl_path=atmosphere/hbl.nsp
override_key=R

I have a kip file only for exfat driver

**Comment by yellows8** [comment]
BOTW version?

**Comment by jul2003** [comment]
1.5.0 eur

**Comment by fincs** [comment]
Can you try the attached hbl.nsp build, and tell me if it solves your problem?
[hbl.zip](https://github.com/switchbrew/nx-hbloader/files/2567848/hbl.zip)

**Comment by jul2003** [comment]
Now it's better.
I'm with atmosphere 0.7.4 and hbmenu is displayed.
But when i try launch an homebrew like Checkpoint to save my games backup it crashes error 2003-0004 but if i do the same through the default setting with album it works , homebrew starts.

**Comment by yellows8** [comment]
What all apps did you try besides Checkpoint? Are you using the latest Checkpoint release?

**Comment by jul2003** [comment]
yes i use the latest Checkpoint release 3.5.0
i have to add that my sd card is exfat and the exfat driver is loaded with a kips in atmosphere kips folder

**Comment by yellows8** [comment]
And plain fat without fs-sysmodule modifying?

**Comment by jul2003** [comment]
same thing with my sd card in fat32 crash

**Comment by jul2003** [comment]
Ok so result with this version is : 
- Super Mario Odyssey title id 0100000000010000 version 1.2.0 : It works
- Zelda breath of the wild title id 01007EF00011E000 version 1.5.0 : It doesn't work error 2003-0004
- 1-2-Switch title id 01000320000CC000 version 1.1.0 : it doesn't work error 2003-0004
- MarioKart 8 Deluxe title id 0100152000022000 version 1.4.0 : it doesn't work error 2003-0004
- Just Dance 2017 title id 0100BCE000598000 version 1.0.0 : it works

And now my sdcard is fat32 i don't load the exfat driver.

**Comment by yellows8** [comment]
I meant homebrew apps.

**Comment by jul2003** [comment]
Oh ok sorry
So through Zelda the result is 
nx-shell v1.05 : error 2003-0004
Homebrew App Store v2.0 : it loads
Checkpoint v3.5.0 : error 2003-0004
Edizon v1.5.1 : error 2003-0004
Tetriswitch v1.1.0 : it loads

Let me know if you want i test other homebrew.

**Comment by yellows8** [comment]
What happens if you press the + button to reload hbmenu, multiple times?

**Comment by jul2003** [comment]
i load hbmenu from my title game then first time i press the + button it crashes error 2003-0004

**Comment by jul2003** [comment]
Hi,

Is there something more we can do on this issue ?

Thanks

**Comment by yellows8** [comment]
Need log from atmo fatal but there isn't a release for that yet. :/

**Comment by yellows8** [comment]
Can you try with atmo 0.8.0 and gist the output log from fatal?

**Comment by jul2003** [comment]
it doesn't create a file on my sd card when it crashed , a picture of the screen is ok for you ?

**Comment by jul2003** [comment]
ok i got it with the sd card in fat32 not exfat. it seems i have problem when i use an exfat sd card.
https://gist.github.com/jul2003/bcbf326a86f34e286c15985980441eb2

**Comment by yellows8** [comment]
:)
