### ISSUE TITLE
Hangs upon launching NRO files on 5.1.0

### ISSUE THREAD

**Issue by fennectech** [switchbrew/nx-hbloader#2]
I compiled a build from here but it doesnt load on 5.1.0   Here is the build i compiled.  
https://github.com/BernardoGiordano/Checkpoint/files/2065308/96AC-42CB.zip

**Comment by yellows8** [comment]
What exactly did you update on SD?

**Comment by fennectech** [comment]
The files in the atmosphere folder   main and main.npdm

**Comment by fennectech** [comment]
Here is my current installation 
[UPDATED.zip](https://github.com/switchbrew/nx-hbloader/files/2065454/UPDATED.zip)

**Comment by fennectech** [comment]
Excuse me?
