### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by eiros** [switchbrew/nx-hbloader#20]
Hbg.shop
Failed to read NSP metadata

DBI
No CNMT file in nsp

Goldleaf crashes

**Comment by fincs** [comment]
nx-hbloader is not a warez NSP; it is an ExeFS NSP. Atmosphère comes bundled with nx-hbloader and nx-hbmenu, so user intervention is not needed to run homebrew.

Piracy is not supported.

**Comment by eiros** [comment]
Thanks, but I understood nothing. I want to run HB menu right from game list (without pressing R on any game) to run not in applet mode. I can't install some nsp and do it like with RetroArch, for example?

**Comment by fincs** [comment]
Atmosphère's default settings will allow you to boot homebrew by holding R while loading any game you have officially installed. You can modify those settings to allow for a game to become the designated homebrew title; which you will launch (without pressing buttons) to boot homebrew. Please refer to Atmosphère's [HBL settings](https://github.com/Atmosphere-NX/Atmosphere/blob/master/common/defaults/loader.ini#L1-L5) section for more details.

Also, please do not install unsigned titles. There are numerous risks involved in their installation (including permanent banning from Nintendo's servers), and it is **completely unnecessary** for the purpose of running homebrew with full privileges.

**Comment by eiros** [comment]
I see now, thanks a lot!
