### ISSUE TITLE
nx-hbloader crashes while running in applet mode alongside some games

### ISSUE THREAD

**Issue by CompSciOrBust** [switchbrew/nx-hbloader#21]
When opening hbmenu as album when running some games (e.g BOTW) nx-hbloader will fatal.
Error code: 2345-0031
Firmware: 8.1.0
Atmosphere version: 0.9.4
[01569072853_010000000000100d.log](https://github.com/switchbrew/nx-hbloader/files/3638719/01569072853_010000000000100d.log)
[01569072853_010000000000100d.zip](https://github.com/switchbrew/nx-hbloader/files/3638720/01569072853_010000000000100d.zip)

**Comment by yellows8** [comment]
What's the game-version, and does it happen with any other titles?

**Comment by CompSciOrBust** [comment]
Botw is version 1.5.0. I'm using a cartridge.
Some people on discord are saying it happens with Link's awakening but I don't know if that's digital or physical or what version.
I have also tested it with YouTube 1.0 digital and Minecraft 1.12.0 digital. Neither of those crash so my  hypothesis is it is something to do with the amount ram the game is using.

**Comment by T-B0ne308** [comment]
I get the exact same issue happens with BOTW v1.6, Links Awakening v1.0 and Bayonetta 2. It does not happen with Dead Cells and The Untitled Goose Game.

Result:                          0x3F59 (2345-0031)

Title ID:                        010000000000100d
Process Name:                    hbloader
Firmware:                        8.1.0 (Atmosphère 0.9.4-master-c62c4846)
General Purpose Registers:
         FP:                     00000000353aee90
         LR:                     00000008355ce114
         SP:                     00000000353aee90
         PC:                     00000008355d5bc8
Start Address:                   0000000835535000
Stack Trace:
        ReturnAddress[00]:       00000008355ce190
        ReturnAddress[01]:       00000008355df01c
        ReturnAddress[02]:       00000008355df0a0
        ReturnAddress[03]:       0000000835535104
        ReturnAddress[04]:       00000000000011fd
        ReturnAddress[05]:       0000000835536760

**Comment by T-B0ne308** [comment]
completely deleting all of atmosphere, and reinstalling it all with just atmosphere, not the kosmos pack and it fixed the crashing for me.

**Comment by yellows8** [comment]
@CompSciOrBust Are you using vanilla atmo release without extra sysmodules?^

**Comment by CompSciOrBust** [comment]
I'm using Hekate and stock Atmos (Fss0). No extra sysmodules.

**Comment by CompSciOrBust** [comment]
Closing because it appears to be a issue with Freebird not hbloader. Maybe it's a bug in hbloader but is only triggered by certain sysmodules? Since no one else reported it in ~5 weeks I think it's probably the former.

**Comment by CompSciOrBust** [comment]
After hearing no one else have this issue for 5 weeks I closed it and then found out @Slluxx has the same problem and doesn't use Freebird.

**Comment by Slluxx** [comment]
BOTW 1.6.0 non cardridge, no freebird.
Emummc 8.1.0 AMS 0.9.4 (Kosmos)

```
Atmosphère Fatal Report (v1.0):
Result:                          0x3FE610 (2016-8179)

Title ID:                        010000000000100d
Process Name:                    hbloader
Firmware:                        8.1.0 (Atmosphère 0.9.4-master-c62c4846)
General Purpose Registers:
         FP:                     000000003a17f7a0
         LR:                     00000000233fd244
         SP:                     000000003a17f7a0
         PC:                     0000000023408070
Start Address:                   0000000023000000
Stack Trace:
        ReturnAddress[00]:       0000000023203af8
        ReturnAddress[01]:       0000000023203890
        ReturnAddress[02]:       0000000023203434
        ReturnAddress[03]:       0000000023203588
        ReturnAddress[04]:       000000002320090c
        ReturnAddress[05]:       00000000231ffc78
        ReturnAddress[06]:       00000000231ffd44
        ReturnAddress[07]:       00000000233d1350
        ReturnAddress[08]:       00000000233d0e28
        ReturnAddress[09]:       00000000230c4838
        ReturnAddress[10]:       00000000230c3ce8
        ReturnAddress[11]:       000000002306c824
        ReturnAddress[12]:       00000000230e8020
        ReturnAddress[13]:       0000000023034564
        ReturnAddress[14]:       00000000230f7474
        ReturnAddress[15]:       0000000023616690
        ReturnAddress[16]:       0000000023615d98
        ReturnAddress[17]:       00000000233e7e68
        ReturnAddress[18]:       00000000233ea2c4
        ReturnAddress[19]:       0000000000000000
```

**Comment by fincs** [comment]
Can you try with normal vanilla Atmosphère, without 3rd party additions?

**Comment by yellows8** [comment]
@Slluxx When exactly does that fatal occur?

**Comment by Slluxx** [comment]
After some playing around i managed to get it after beeing in zelda, pressing the home button and opening the hbl via R + Gallery a few times.

This also happens in a clean ams only install, though i will remove it again now cause i use kosmos just like most of the people anyway

**Comment by yellows8** [comment]
So it only happens prior to hbmenu being displayed, not when launching some hb-app?

**Comment by CompSciOrBust** [comment]
I'm using Stock Asmosphere and can't reproduce it the way Slluxx described but maybe that's because I'm using a cart version of botw? I'm using the same set up as before (atmos 0.9.4, fw 8.1) but I updated botw to version 1.6.0.

**Comment by Slluxx** [comment]
The fatal occurs right on launch of the hbl, not when trying to launch a hb. though, before the fatal happened, i actually was able and did start homebrew (then back into the game, pressing home, trying again etc till it crashed).

**Comment by yellows8** [comment]
What version of hbl/hbmenu are you using?(Make sure they're the latest)

**Comment by CompSciOrBust** [comment]
I'm using hbmenu 3.1.1 and hbloader 2.2.0.

**Comment by ZTetriminos** [comment]
Bump. As of 2023, using nx-hbloader v2.4.3 and hbmenu 3.5.1 and latest firmware and Atmosphère, this issue still happens.
[Here is a more detailed reddit post I've wrote](https://www.reddit.com/r/SwitchPirates/comments/12eti23/hbmenu_hangs_when_launched_in_applet_mode_had/)
Games where I recall this happening: Pokémon Violet, Klonoa Phantasy Reverie and Atelier Escha & Logy.
The only difference is that it does not show any error message, just hangs and that's the end of it.

**Comment by SciresM** [comment]
I am able to open hbmenu as applet totally fine with Pokémon scarlet/violet open. Note that if you have custom sysmodules or themes or whatever, this may increase applet memory usage, and then you'll need to edit your hbmenu config to reserve less memory accordingly. 

That is in fact not an atmosphere or hbmenu bug; if you think it is, please reproduce with just atmosphere and hbmenu and absolutely zero non-default config.

**Comment by BerrieBuffel** [comment]
> Bump. As of 2023, using nx-hbloader v2.4.3 and hbmenu 3.5.1 and latest firmware and Atmosphère, this issue still happens.
> [Here is a more detailed reddit post I've wrote]
> 
> [MOD NOTE: Removed link to piracy website]
> 
> Games where I recall this happening: Pokémon Violet, Klonoa Phantasy Reverie and Atelier Escha & Logy.
> The only difference is that it does not show any error message, just hangs and that's the end of it.

I have the exact same problem with Hyrule warriors age of calamity

**Comment by yellows8** [comment]
@BerrieBuffel Doesn't happen here (no game-update installed however). Check `Note that if you have custom sysmodules or themes or whatever,` (/atmosphere/contents/) and `absolutely zero non-default config.` above.
