### ISSUE TITLE
An album applet and non applet user option?

### ISSUE THREAD

**Issue by KMZoilus** [switchbrew/nx-hbloader#23]
Love the HBL... BUT I can't stand that now going through the album forces HBMENU to open in applet mode. So before you could have a game running  and open up and use HBm/HBL going through the album, now games must be shut down. Can the USER be given the option to select/change whether they want it to open up as an applet or full version through the album? Maybe change something in the settings ini, or have 2 versions of this or something like that. I've seen various people complain about the applet version in album across forums, comments on YT ..etc etc. I'm sure if any option can be given to the user to choose or change this, it would be great. Thanks

**Comment by yellows8** [comment]
Hold the R-button or change your config. https://github.com/Atmosphere-NX/Atmosphere/issues

**Comment by SciresM** [comment]
The Switch's OS only supports one application at a time. If a game is open, HBL must be an applet. It's an OS restriction.
