### ISSUE TITLE
Crash when installing nsp with goldleaf (atmosphere w/kosmos) 0x4a8

### ISSUE THREAD

**Issue by Autumnium** [switchbrew/nx-hbloader#24]
Error: when installing hbl.nsp using goldleaf, switch crashes when in applet mode, and app crash when using it on normal mode

it used to work just fine in my prior installation of atmosphere without kosmos, but when i did a fresh install of atmos w/kosmos, it crashes upon install

**Comment by fincs** [comment]
hbl.nsp is not an "installable" (aka warez) nsp. It is an ExeFS image; that is used with Atmosphère's first class hbloader support. Do not use goldleaf or any similar installer apps; they are completely unnecessary for running homebrew and only entail a ban risk.
