### ISSUE TITLE
Feature request: use hotkeys to open specific homebrew

### ISSUE THREAD

**Issue by Heartbeat-Heartbreak** [switchbrew/nx-hbloader#25]
hbl.zip *(link removed)*
This is a modified hbl (version 2.2.0-),  I found it from the old version *(reference to piracy tool removed)*.
Replace "hbl.nsp" and "hbl.json" into the atmosphere folder, then edit the hbl.json, you can use the hotkeys to open specific homebrew.
example:

> "ZL": "sdmc:/switch/edizon.nro"

Click the album and then hold the "ZL" to quickly open Edizon.
> "A": "sdmc:/switch/nxmtp.nro"

Click the album and then hold the "A" to quickly open nxmtp.

It support a lot of hotkeys. 
I have used this function for some time and I had some problems: this modified hbl use too much applet memory, when I open the system keyboard on some homebrew, the atmosphere was crashes. I have tried editing atmosphere system.ini,  but it didn't work.
In the latest version of *(removed reference to piracy tool)*, they removed this hbl. Looks like they don't plan to update anymore.
I think that is a very very useful feature, can you add it to the official version?
My english is not very well, hope you 
can understand what I mean and thanks for your patience.

**Comment by fincs** [comment]
Hi,

We don't recommend users to use third party modified versions of hbloader, especially not versions that are outdated and have been bundled together with piracy tools we definitely do not want to interact with.

With that said, one of the main functions of nx-hbloader is to launch nx-hbmenu. This fact is engrained in nx-hbmenu, which also has a double function as setting up several applet related aspects of the homebrew environment. For this reason, we consider it undefined behavior when nx-hbmenu is bypassed as the first NRO to be launched. This means that unfortunately it is not possible to implement the feature you're asking for in a way that is guaranteed to work with every single piece of homebrew.
