### ISSUE TITLE
Issue installing with Tinfoil.

### ISSUE THREAD

**Issue by ChocoCheeese07** [switchbrew/nx-hbloader#33]
When I try to install with tinfoil it says "Failed to read NSP metadata". Is here something specific I have to do? I'm on latest fw and atmosphere, and my sigpatches are set up.

**Comment by fincs** [comment]
hbloader is not a piracy related "installable" NSP. This is an ExeFS NSP, which is loaded natively by Atmosphère's built-in homebrew support. Atmosphère ships with a copy of hbloader already, so you don't need to set up any additional software on your Switch.

"Sigpatches" and "Tinfoil" are exclusively piracy oriented and are completely irrelevant to homebrew.
