### ISSUE TITLE
hbloader 2.4.2 crash in homebrew

### ISSUE THREAD

**Issue by lowburger** [switchbrew/nx-hbloader#37]
Hi,

I may ask if new version is safe for use? I have homebrew crash when use in firmware 15.0.0 and atmosphere 1.4.0 and open jksv homebrew.

https://gist.github.com/lowburger/281363aee88211e78cf6b3fc89f1198f

**Comment by josete2k** [comment]
Same on MTP in DBI...

**Comment by fincs** [comment]
Please grab https://github.com/switchbrew/nx-hbloader/releases/tag/v2.4.3.
