### ISSUE TITLE
Error while launching hbloader

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [switchbrew/nx-hbloader#5]
While launching hbloader through Album's exefs, (say, why do we use nsp and not nso? nspwn?), I get error ``2144-0001``, which *seems* to be related to EC (Shop) according to Switchbrew's "Error codes" page.

Am I doing something wrong?

**Comment by yellows8** [comment]
"(say, why do we use nsp and not nso? nspwn?)" <- This makes no sense. .nsp is just a container for exefs which contains NSO etc...

"through Album's exefs" <- More details?

**Comment by ThatNerdyPikachu** [comment]
1. Ah, sorry. Thought .nsp was a PFS0
2. Atmosphere's loader sysmodule. The contents of my atmosphere/titles/010000000000100D:
[010000000000100D.zip](https://github.com/switchbrew/nx-hbloader/files/2281152/010000000000100D.zip)
(was originally meant to use 00000000001003, but switched to album to see if that was the issue)

**Comment by yellows8** [comment]
1) It is, see above regarding contents.
2) Try using .nsp (if you're using latest loader sysmodule).

**Comment by ThatNerdyPikachu** [comment]
2. You mean rename ``main`` to ``exefs.nsp`` as per https://github.com/Atmosphere-NX/Atmosphere/commit/3a2520a3b75c1c3fca8a39d35f0a154c5bb59217?

**Comment by yellows8** [comment]
no ...

**Comment by yellows8** [comment]
Build nx-hbloader then copy hbl.nsp to exefs.nsp.

**Comment by ThatNerdyPikachu** [comment]
``main`` *is* the latest hbl.nsp
okay

**Comment by yellows8** [comment]
main is the NSO.

**Comment by ThatNerdyPikachu** [comment]
thanks for all your help
