### ISSUE TITLE
Compilation error. 

### ISSUE THREAD

**Issue by fennectech** [switchbrew/nx-hbloader#7]
Doesnt compile.  
[fennectech@Aluminum ~/nx-hbloader]$  make
main.c
aarch64-none-elf-gcc -MMD -MP -MF /home/fennectech/nx-hbloader/build/main.d -g -Wall -O2 -ffunction-sections -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIE  -I/home/fennectech/nx-hbloader/include -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/home/fennectech/nx-hbloader/build -D__SWITCH__ -c /home/fennectech/nx-hbloader/source/main.c -o main.o 
/home/fennectech/nx-hbloader/source/main.c: In function 'getIsApplication':
/home/fennectech/nx-hbloader/source/main.c:132:14: warning: implicit declaration of function 'pmshellGetApplicationPid'; did you mean 'pmdmntGetApplicationPid'? [-Wimplicit-function-declaration]
         rc = pmshellGetApplicationPid(&app_pid);
              ^~~~~~~~~~~~~~~~~~~~~~~~
              pmdmntGetApplicationPid
/home/fennectech/nx-hbloader/source/main.c: In function 'loadNro':
/home/fennectech/nx-hbloader/source/main.c:341:38: error: 'EnvAppletFlags_ApplicationOverride' undeclared (first use in this function); did you mean 'AppletType_Application'?
         entry_AppletType->Value[1] = EnvAppletFlags_ApplicationOverride;
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                      AppletType_Application
/home/fennectech/nx-hbloader/source/main.c:341:38: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:19: main.o] Error 1
make: *** [Makefile:118: build] Error 2

**Comment by yellows8** [comment]
Requires git libnx atm, can use the release build instead.
