### ISSUE TITLE
System crash when hbloader is being loaded as an exefs (2345-0031)

### ISSUE THREAD

**Issue by jusefn** [switchbrew/nx-hbloader#8]
Horizon Version: 6.0.1
Atmosphere Version: 0.7.1
hbloader version: 2.0.0
Crash Error: 2345-0031
SDCard format: FAT32

Tested titles:
Mega Man 11 Demo Version (titleid: 010076800B06E000)
The Legend of Zelda: Breath of the Wild (titleid: 01007EF00011E000)

HBL through Album runs just fine.

**Comment by yellows8** [comment]
This is being thrown by hbmenu right, as in nothing displayed after launching the title before the fatalerr?

**Comment by daJoschi** [comment]
I selected the user, the switch did it's title boot animation just to be abrupted with the crash.

**Comment by yellows8** [comment]
Need to build a test app for this later - wondering if it's a 6.x issue.

**Comment by yellows8** [comment]
Try with this at "/hbmenu.nro" & post the content of "/libnx_log" (this is not nx-hbmenu).

https://www.dropbox.com/s/2f2qvyz1hzhk99t/am_test.nro?dl=0

**Comment by daJoschi** [comment]
```
__nx_applet_type: 0x2
appletInitialize() rc = 0x19680
```
`
Here is the output

**Comment by yellows8** [comment]
It's using AppletType_LibraryApplet, so it's not detecting that it's running as an application. :-/
