### ISSUE TITLE
hbloader not detecting that I'm running through an app, so it loads NROs as an Applet instead of SystemApplication

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [switchbrew/nx-hbloader#9]

**Comment by yellows8** [comment]
loader.ini? #8

**Comment by ThatNerdyPikachu** [comment]
no, replacing an app's exefs through loader, but not using atms' default impl
before this change, switching https://github.com/switchbrew/nx-hbloader/blob/master/source/main.c#L328 to SystemApplication made it work

**Comment by yellows8** [comment]
It *needs* atmo...

**Comment by ThatNerdyPikachu** [comment]
is there some specific reason why (i.e., a flag not being set or something)?

**Comment by yellows8** [comment]
Atmo overrides the application-type in the NPDM with the one from the original title.
